### ISSUE TITLE
Add support for Rival 100

### ISSUE THREAD

**Issue by nixi-awoo** [nixi-awoo/rivalctl#1]
- [x] commit
- [ ] reset
- [ ] profile
- [x] color (wheel and logo colour cannot be set separately)
- [x] cpi
- [x] polling rate

**Comment by m9rbid** [comment]
At least the CPI setup for the Rival 100 doesn't seem to work. I get the following error after executing "rivalctl --commit --cpi2 500":

> Traceback (most recent call last):
  File "/usr/local/bin/rivalctl", line 9, in <module>
    load_entry_point('rivalctl==0.1', 'console_scripts', 'rivalctl')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/rivalctl-0.1-py2.7.egg/rival/__init__.py", line 1, in <module>
    from rival import *
  File "/usr/local/lib/python2.7/dist-packages/rivalctl-0.1-py2.7.egg/rival/rival.py", line 8, in <module>
    from rival import hidrawpure as hidraw
ImportError: cannot import name hidrawpure

Any idea how to fix this?

Best,

m9rbid

**Comment by nixi-awoo** [comment]
@m9rbid 
Make sure you are using pyton3.
