### ISSUE TITLE
Add support for Rival 300 (new firmware)

### ISSUE THREAD

**Issue by ghost** [nixi-awoo/rivalctl#3]
Getting the following error under Ubuntu 16.04:
```
sagcan@peace:~/rivalctl$ sudo rivalctl --logo-color green
Traceback (most recent call last):
  File "/usr/local/bin/rivalctl", line 9, in <module>
    load_entry_point('rivalctl==0.1', 'console_scripts', 'rivalctl')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/rivalctl-0.1-py2.7.egg/rival/__init__.py", line 1, in <module>
    from rival import *
  File "/usr/local/lib/python2.7/dist-packages/rivalctl-0.1-py2.7.egg/rival/rival.py", line 8, in <module>
    from rival import hidrawpure as hidraw
ImportError: cannot import name hidrawpure
```
Any way I can fix this (I'm in the dialout group, so write permissions should be present)?

**Comment by nixi-awoo** [comment]
The program should be installed and run under Python 3. Try that and post the results. If that does not work, share your device model and I will look into it.

**Comment by ghost** [comment]
I've reinstalled it with python3 and it worked so far (no errors). However the commands do not change anything on my mouse (e.g. rivalctl --logo-color green doesn't do anything, no errors, color stays the same). 
Device Model is the Rival 300 Black
lsusb gives the following output:
`Bus 003 Device 002: ID 1038:1710 SteelSeries ApS `

**Comment by nixi-awoo** [comment]
I have added an experimental code to support Rival 300 Black which was untested so far. The 300 Black model uses a different set of instructions. I will see what I can do about it. I have plans to rewrite the whole tool and re-release it, since the code I forked does not really play well with different HIDs.

**Comment by ghost** [comment]
Cool, thanks! I'll just wait for it :)

**Comment by nixi-awoo** [comment]
If you get tired of waiting, try using a tool called 'rivalcfg' by @flozz (https://github.com/flozz/rivalcfg). It is build originally by flozz and the code should be cleaner. It might even support Rival 300 Black out of the box. I am going to comment on this issue if I ever finish the rewrite (possibly in C).

**Comment by ghost** [comment]
I actually have tried rivalcfg in the past but had no luck. Might open an issue there as well.

**Comment by nixi-awoo** [comment]
Well then, I will keep you posted. The rewritten tool will probably be hosted on gitlab though, since I am trying to migrate away from github.

**Comment by flozz** [comment]
Hello,

`rivalcfg` is compatible with the Rival 300 (and you mouse appear to be a Rival 300 regarding to the vendor/product id `1038:1710`).

But someone reported that there is a new firmware that changes the instruction set of this mouse: https://github.com/flozz/rivalcfg/issues/5

Maybe a new reverse engineering of the Rival 300 will be necessary to support new versions...

**Comment by ghost** [comment]
@flozz Good to know. Thank you very much!
