### ISSUE TITLE
Add support for Rival 700

### ISSUE THREAD

**Issue by nixtux** [nixi-awoo/rivalctl#4]
Hey im getting this error under ubuntu 16.04

> rivalctl --logo-color 3
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rivalctl-0.1-py3.5.egg/rival/rival.py", line 63, in open_device
    device = Rival100(dev_path = dev_path)
  File "/usr/local/lib/python3.5/dist-packages/rivalctl-0.1-py3.5.egg/rival/rival.py", line 270, in __init__
    Rival.__init__(self, hid_id, dev_path)
  File "/usr/local/lib/python3.5/dist-packages/rivalctl-0.1-py3.5.egg/rival/rival.py", line 176, in __init__
    device = open_hiddevice(hid_id, dev_path)
  File "/usr/local/lib/python3.5/dist-packages/rivalctl-0.1-py3.5.egg/rival/rival.py", line 42, in open_hiddevice
    device =  hidraw.HIDRaw(open(dev_path, 'w+'))
TypeError: invalid file: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/rivalctl", line 9, in <module>
    load_entry_point('rivalctl==0.1', 'console_scripts', 'rivalctl')()
  File "/usr/local/lib/python3.5/dist-packages/rivalctl-0.1-py3.5.egg/rival/rivalctl.py", line 66, in main
    _main(args)
  File "/usr/local/lib/python3.5/dist-packages/rivalctl-0.1-py3.5.egg/rival/rivalctl.py", line 19, in _main
    device = open_device()
  File "/usr/local/lib/python3.5/dist-packages/rivalctl-0.1-py3.5.egg/rival/rival.py", line 65, in open_device
    device = Rival(dev_path = dev_path)
  File "/usr/local/lib/python3.5/dist-packages/rivalctl-0.1-py3.5.egg/rival/rival.py", line 176, in __init__
    device = open_hiddevice(hid_id, dev_path)
  File "/usr/local/lib/python3.5/dist-packages/rivalctl-0.1-py3.5.egg/rival/rival.py", line 42, in open_hiddevice
    device =  hidraw.HIDRaw(open(dev_path, 'w+'))
TypeError: invalid file: None

Any idea whats wrong, im using a SteelSeries Rival 700 Gaming Mouse

**Comment by nixtux** [comment]
Ah just noticed its not supported yet.

**Comment by nixi-awoo** [comment]
Exactly, the support for this HID is not included. If you manage to capture all the necessary traffic, I can implement it. As mentioned in a previous thread, I am working on a rewrite of this tool in C with wider support, but the development is on hold since I have a lot to do at school.
