### ISSUE TITLE
Error executing with Python 3?

### ISSUE THREAD

**Issue by cgimenes** [nixi-awoo/rivalctl#5]
Hi,
when I try to execute any command (even with root permission), the application displays this exception:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/rival/rival.py", line 63, in open_device
    device = Rival100(dev_path = dev_path)
  File "/usr/lib/python3.6/site-packages/rival/rival.py", line 270, in __init__
    Rival.__init__(self, hid_id, dev_path)
  File "/usr/lib/python3.6/site-packages/rival/rival.py", line 176, in __init__
    device = open_hiddevice(hid_id, dev_path)
  File "/usr/lib/python3.6/site-packages/rival/rival.py", line 42, in open_hiddevice
    device =  hidraw.HIDRaw(open(dev_path, 'w+'))
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rivalctl", line 11, in <module>
    load_entry_point('rivalctl==0.1', 'console_scripts', 'rivalctl')()
  File "/usr/lib/python3.6/site-packages/rival/rivalctl.py", line 66, in main
    _main(args)
  File "/usr/lib/python3.6/site-packages/rival/rivalctl.py", line 19, in _main
    device = open_device()
  File "/usr/lib/python3.6/site-packages/rival/rival.py", line 65, in open_device
    device = Rival(dev_path = dev_path)
  File "/usr/lib/python3.6/site-packages/rival/rival.py", line 176, in __init__
    device = open_hiddevice(hid_id, dev_path)
  File "/usr/lib/python3.6/site-packages/rival/rival.py", line 42, in open_hiddevice
    device =  hidraw.HIDRaw(open(dev_path, 'w+'))
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I'm using:
Arch Linux kernel 4.8.13-1
Python 3.6.0

And installed from this AUR's package: https://aur.archlinux.org/packages/rivalctl-git/

**Comment by hymair** [comment]
I have exactly the same issue.

Rival 110
Arch Linux 4.13.9

**Comment by cgimenes** [comment]
I'm using this package now: https://aur.archlinux.org/packages/rivalcfg-git/

**Comment by hymair** [comment]
It was the first one I tried but "No supported devices found"...
